[package]
name = "ziwei"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "A Rust library for Ziwei Doushu chart construction"

[dependencies]
arrayvec = { version = "0.7.8", default-features = false }

[lints]
workspace = true
